routes/admin.php
<?php

    Route::GET('/', 'AdminController@index')->name('admin.home');
    // Login and Logout
    Route::GET('/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::POST('/login', 'LoginController@login');
    Route::POST('/logout', 'LoginController@logout')->name('admin.logout');

    // Password Resets
    Route::POST('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::GET('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::POST('/password/reset', 'ResetPasswordController@reset');
    Route::GET('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::GET('/password/change', 'AdminController@showChangePasswordForm')->name('admin.password.change');
    Route::POST('/password/change', 'AdminController@changePassword');

    // Register Admins
    Route::get('/register', 'RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('/register', 'RegisterController@register');
    Route::get('/{admin}/edit', 'RegisterController@edit')->name('admin.edit');
    Route::delete('/{admin}', 'RegisterController@destroy')->name('admin.delete');
    Route::patch('/{admin}', 'RegisterController@update')->name('admin.update');

    // Admin Lists
    Route::get('/show', 'AdminController@show')->name('admin.show');

    // Admin Roles
    Route::post('/{admin}/role/{role}', 'AdminRoleController@attach')->name('admin.attach.roles');
    Route::delete('/{admin}/role/{role}', 'AdminRoleController@detach');

    // Roles
    Route::get('/roles', 'RoleController@index')->name('admin.roles');
    Route::get('/role/create', 'RoleController@create')->name('admin.role.create');
    Route::post('/role/store', 'RoleController@store')->name('admin.role.store');
    Route::delete('/role/{role}', 'RoleController@destroy')->name('admin.role.delete');
    Route::get('/role/{role}/edit', 'RoleController@edit')->name('admin.role.edit');
    Route::patch('/role/{role}', 'RoleController@update')->name('admin.role.update');

    Route::fallback(function () {
        return abort(404);
    });

routes/dashboard.php
<?php
Route::resource('yearly', 'Achievement\YearlyAchievementController');
Route::resource('monthly', 'Achievement\MonthlyAchievementController');
Route::resource('daily', 'Achievement\DailyAchievementController');
Route::get('daily/monthly/yearly/{id}', 'Achievement\DailyAchievementController@monthlyByYearly')->name('monthly.by.yearly');
Route::get('daily/monthly/{id}', 'Achievement\DailyAchievementController@dailyByMonthly')->name('daily.by.monthly');
Route::get('generate/yearly/{id}', 'Achievement\MonthlyAchievementController@generateByYearly')->name('generate.by.yearly');
Route::get('generate/monthly/{id}', 'Achievement\MonthlyAchievementController@generateByMonthly')->name('generate.by.monthly');
Route::post('monthly/save/generate/target', 'Achievement\MonthlyAchievementController@monthlySaveGenerateTarget')->name('monthly.save.generate.target');
Route::post('daily/save/generate/target', 'Achievement\DailyAchievementController@dailySaveGenerateTarget')->name('daily.save.generate.target');

/* Inbound */
Route::resource('inbound/daily-inbound', 'Inbound\DailyInboundController');
Route::resource('inbound/monthly-inbound', 'Inbound\MonthlyInboundController');
Route::resource('inbound/yearly-inbound', 'Inbound\YearlyInboundController');

routes/user.php
<?php
Route::resource('user.profile', 'UserProfileController');
Route::resource('cart', 'CartController');
Route::resource('transaction', 'TransactionController');
Route::resource('transaction.detail', 'TransactionDetailController');
Route::resource('transaction.vendor', 'TransactionVendorController');
Route::resource('transaction.vendor.detail', 'TransactionVendorDetailController');

Route::put('user.change.password', 'UserProfileController@change_password')->name('user.change.password');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/partials/attributs/message.blade.php
@if(session('success'))
	<div class="ui mini modal modal-success">
		<i class="close icon"></i>
		<div class="header">Success</div>
		<div class="content text-center">
			<p>{{ session('success') }}</p>
		</div>
		<div class="actions">
			<div class="ui positive right labeled icon button">
				Ok<i class="checkmark icon"></i>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$(document).ready(function() {
			$('.ui.modal.modal-success').modal({detachable: false}).modal('show');
		});
	</script>
@endif

@if(session('message') || session('status'))
	<div class="ui mini modal modal-message">
		<i class="close icon"></i>
		<div class="header">Message</div>
		<div class="content text-center">
			@if(session('message'))
				<p>{{ session('message') }}</p>
			@elseif(session('status'))
				<p>{{ session('status') }}</p>
			@endif
		</div>
		<div class="actions">
			<div class="ui positive right labeled icon button">
				Ok<i class="checkmark icon"></i>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$(document).ready(function() {
			$('.ui.modal.modal-message').modal({detachable: false}).modal('show');
		});
	</script>
@endif

@if(session('errors'))
	<div class="ui mini modal modal-error">
		<i class="close icon"></i>
		<div class="header">Error</div>
		<div class="content text-center">
			<p>{{ session('errors') }}</p>
		</div>
		<div class="actions">
			<div class="ui negative right labeled icon button">
				Ok<i class="checkmark icon"></i>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$(document).ready(function() {
			$('.ui.modal.modal-error').modal({detachable: false}).modal('show');
		});
	</script>
@endif

resources/views/admin/partials/attributs/nav.blade.php
<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">
	<div class="navbar-header">
		<button type="button" class="navbar-toggler hamburger hamburger-close navbar-toggler-left hided" data-toggle="menubar">
			<span class="sr-only">Toggle navigation</span>
			<span class="hamburger-bar"></span>
		</button>
		<button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-collapse" data-toggle="collapse">
			<i class="icon md-more" aria-hidden="true"></i>
		</button>

		<div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
			<img class="navbar-brand-logo" src="{{ asset('public/plugin/mui-trade-template/mmenu/assets/images/logo.png') }}" title="Remark">
			<span class="navbar-brand-text hidden-xs-down"> Remark</span>
		</div>

		<button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-search" data-toggle="collapse">
			<span class="sr-only">Toggle Search</span>
			<i class="icon md-search" aria-hidden="true"></i>
		</button>
	</div>

	<div class="navbar-container container-fluid">
		<!-- Navbar Collapse -->
		<div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
			<!-- Navbar Toolbar -->
			<ul class="nav navbar-toolbar">
				<li class="nav-item hidden-float" id="toggleMenubar">
					<a class="nav-link" data-toggle="menubar" href="#" role="button">
						<i class="icon hamburger hamburger-arrow-left">
							<span class="sr-only">Toggle menubar</span>
							<span class="hamburger-bar"></span>
						</i>
					</a>
				</li>

				<li class="nav-item hidden-sm-down" id="toggleFullscreen">
					<a class="nav-link icon icon-fullscreen" data-toggle="fullscreen" href="#" role="button">
						<span class="sr-only">Toggle fullscreen</span>
					</a>
				</li>

				<li class="nav-item hidden-float">
					<a class="nav-link icon md-search" data-toggle="collapse" href="#" data-target="#site-navbar-search" role="button">
						<span class="sr-only">Toggle Search</span>
					</a>
				</li>

				<li class="nav-item dropdown dropdown-fw dropdown-mega">
					<a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false" data-animation="fade" role="button">Scranaver <i class="icon md-chevron-down" aria-hidden="true"></i></a>
					<div class="dropdown-menu" role="menu">
						<div class="mega-content">
							<div class="row">
								<div class="col-md-4">
									<h5>UI Kit</h5>
									<ul class="blocks-2">
										<li class="mega-menu m-0">
											<ul class="list-icons">
												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="advanced/animation.html">Animation</a>
												</li>

												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="uikit/buttons.html">Buttons</a>
												</li>

												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="uikit/colors.html">Colors</a>
												</li>

												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="uikit/dropdowns.html">Dropdowns</a>
												</li>

												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="uikit/icons.html">Icons</a>
												</li>

												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="advanced/lightbox.html">Lightbox</a>
												</li>
											</ul>
										</li>

										<li class="mega-menu m-0">
											<ul class="list-icons">
												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="uikit/modals.html">Modals</a>
												</li>

												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="uikit/panel-structure.html">Panels</a>
												</li>

												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="structure/overlay.html">Overlay</a>
												</li>

												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="uikit/tooltip-popover.html ">Tooltips</a>
												</li>

												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="advanced/scrollable.html">Scrollable</a>
												</li>

												<li>
													<i class="md-chevron-right" aria-hidden="true"></i>
													<a href="uikit/typography.html">Typography</a>
												</li>
											</ul>
										</li>
									</ul>
								</div>

								<div class="col-md-4">
									<h5>Media<span class="badge badge-pill badge-success">4</span></h5>
									<ul class="blocks-3">
										<li>
											<a class="thumbnail m-0" href="javascript:void(0)">
												<img class="w-full" src="{{ asset('public/plugin/mui-trade-template/global/photos/placeholder.png') }}" alt="..." />
											</a>
										</li>

										<li>
											<a class="thumbnail m-0" href="javascript:void(0)">
												<img class="w-full" src="{{ asset('public/plugin/mui-trade-template/global/photos/placeholder.png') }}" alt="..." />
											</a>
										</li>

										<li>
											<a class="thumbnail m-0" href="javascript:void(0)">
												<img class="w-full" src="{{ asset('public/plugin/mui-trade-template/global/photos/placeholder.png') }}" alt="..." />
											</a>
										</li>

										<li>
											<a class="thumbnail m-0" href="javascript:void(0)">
												<img class="w-full" src="{{ asset('public/plugin/mui-trade-template/global/photos/placeholder.png') }}" alt="..." />
											</a>
										</li>

										<li>
											<a class="thumbnail m-0" href="javascript:void(0)">
												<img class="w-full" src="{{ asset('public/plugin/mui-trade-template/global/photos/placeholder.png') }}" alt="..." />
											</a>
										</li>

										<li>
											<a class="thumbnail m-0" href="javascript:void(0)">
												<img class="w-full" src="{{ asset('public/plugin/mui-trade-template/global/photos/placeholder.png') }}" alt="..." />
											</a>
										</li>
									</ul>
								</div>

								<div class="col-md-4">
									<h5 class="mb-0">Accordion</h5>
									<!-- Accordion -->
									<div class="panel-group panel-group-simple" id="siteMegaAccordion" aria-multiselectable="true" role="tablist">
										<div class="panel">
											<div class="panel-heading" id="siteMegaAccordionHeadingOne" role="tab">
												<a class="panel-title" data-toggle="collapse" href="#siteMegaCollapseOne" data-parent="#siteMegaAccordion" aria-expanded="false" aria-controls="siteMegaCollapseOne">
													Collapsible Group Item #1
												</a>
											</div>

											<div class="panel-collapse collapse" id="siteMegaCollapseOne" aria-labelledby="siteMegaAccordionHeadingOne" role="tabpanel">
												<div class="panel-body">
													De moveat laudatur vestra parum doloribus labitur sentire partes, eripuit praesenti congressus ostendit alienae, voluptati ornateque accusamus clamat reperietur convicia albucius.
												</div>
											</div>
										</div>

										<div class="panel">
											<div class="panel-heading" id="siteMegaAccordionHeadingTwo" role="tab">
												<a class="panel-title collapsed" data-toggle="collapse" href="#siteMegaCollapseTwo" data-parent="#siteMegaAccordion" aria-expanded="false" aria-controls="siteMegaCollapseTwo">
													Collapsible Group Item #2
												</a>
											</div>

											<div class="panel-collapse collapse" id="siteMegaCollapseTwo" aria-labelledby="siteMegaAccordionHeadingTwo" role="tabpanel">
												<div class="panel-body">
													Praestabiliorem. Pellat excruciant legantur ullum leniter vacare foris voluptate loco ignavi, credo videretur multoque choro fatemur mortis animus adoptionem, bello statuat expediunt naturales.
												</div>
											</div>
										</div>

										<div class="panel">
											<div class="panel-heading" id="siteMegaAccordionHeadingThree" role="tab">
												<a class="panel-title collapsed" data-toggle="collapse" href="#siteMegaCollapseThree" data-parent="#siteMegaAccordion" aria-expanded="false" aria-controls="siteMegaCollapseThree">
													Collapsible Group Item #3
												</a>
											</div>

											<div class="panel-collapse collapse" id="siteMegaCollapseThree" aria-labelledby="siteMegaAccordionHeadingThree" role="tabpanel">
												<div class="panel-body">
													Horum, antiquitate perciperet d conspectum locus obruamus animumque perspici probabis suscipere. Desiderat magnum, contenta poena desiderant concederetur menandri damna disputandum corporum.
												</div>
											</div>
										</div>
									</div>
									<!-- End Accordion -->
								</div>
							</div>
						</div>
					</div>
				</li>
			</ul>
			<!-- End Navbar Toolbar -->

			<!-- Navbar Toolbar Right -->
			<ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
				<li class="nav-item dropdown">
					<a class="nav-link navbar-avatar" data-toggle="dropdown" href="#" aria-expanded="false" data-animation="scale-up" role="button">
						<span class="avatar avatar-online">
							<img src="{{ asset('public/plugin/mui-trade-template/global/portraits/5.jpg') }}" alt="..."><i></i>
						</span>
					</a>
					<div class="dropdown-menu" role="menu">
						<a class="dropdown-item" href="javascript:void(0)" role="menuitem">
							<i class="icon md-settings" aria-hidden="true"></i> Settings
						</a>

						<div class="dropdown-divider"></div>

						<a class="dropdown-item" href="{{ route('admin.logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" role="menuitem">
							<i class="icon md-power" aria-hidden="true"></i>{{ __('Logout') }}
							<form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
								@csrf
							</form>
						</a>
					</div>
				</li>
			</ul>
			<!-- End Navbar Toolbar Right -->
		</div>
		<!-- End Navbar Collapse -->

		<!-- Site Navbar Seach -->
		<div class="collapse navbar-search-overlap" id="site-navbar-search">
			<form role="search">
				<div class="form-group">
					<div class="input-search">
						<i class="input-search-icon md-search" aria-hidden="true"></i>
						<input type="text" class="form-control" name="site-search" placeholder="Search...">
						<button type="button" class="input-search-close icon md-close" data-target="#site-navbar-search" data-toggle="collapse" aria-label="Close"></button>
					</div>
				</div>
			</form>
		</div>
		<!-- End Site Navbar Seach -->
	</div>
</nav>

resources/views/admin/partials/attributs/sidebar.blade.php
<div class="site-menubar">
    <ul class="site-menu">
        <li class="site-menu-item {{ Request::is('admin') ? 'active' : '' }}">
            <a class="animsition-link" href="{{ route('admin.home') }}">
                <i class="site-menu-icon md-view-dashboard" aria-hidden="true"></i>
                <span class="site-menu-title">Dashboard</span>
            </a>
        </li>

        <li class="site-menu-item has-sub {{ Request::is('admin/register', 'admin/show', 'admin/roles', 'admin/role') ? 'active' : '' }}">
            <a href="javascript:void(0)">
                <i class="site-menu-icon md-view-compact" aria-hidden="true"></i>
                <span class="site-menu-title">Admin</span>
                <span class="site-menu-arrow"></span>
            </a>
            <ul class="site-menu-sub">
                <li class="site-menu-item {{ Request::is('admin/register') ? 'active' : '' }}">
                    <a class="animsition-link" href="{{ route('admin.register') }}">
                        <span class="site-menu-title">Register</span>
                    </a>
                </li>

                <li class="site-menu-item {{ Request::is('admin/show') ? 'active' : '' }}">
                    <a class="animsition-link" href="{{ route('admin.show') }}">
                        <span class="site-menu-title">View</span>
                    </a>
                </li>

                <li class="site-menu-item {{ Request::is('admin/role', 'admin/roles') ? 'active' : '' }}">
                    <a href="javascript:void(0)">
                        <span class="site-menu-title">Role</span>
                        <span class="site-menu-arrow"></span>
                    </a>
                    <ul class="site-menu-sub">
                        <li class="site-menu-item {{ Request::is('admin/role/create') ? 'active' : '' }}">
                            <a class="animsition-link" href="{{ route('admin.role.create') }}">
                                <span class="site-menu-title">Create</span>
                            </a>
                        </li>

                        <li class="site-menu-item {{ Request::is('admin/roles') ? 'active' : '' }}">
                            <a class="animsition-link" href="{{ route('admin.roles') }}">
                                <span class="site-menu-title">View</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>

        <li class="site-menu-item has-sub {{ Request::is('admin/yearly', 'admin/monthly', 'admin/daily') ? 'active' : '' }}">
            <a href="javascript:void(0)">
                <i class="site-menu-icon md-view-compact" aria-hidden="true"></i>
                <span class="site-menu-title">Achievement</span>
                <span class="site-menu-arrow"></span>
            </a>
            <ul class="site-menu-sub">
                <li class="site-menu-item {{ Request::is('admin/yearly') ? 'active' : '' }}">
                    <a class="animsition-link" href="{{ route('yearly.index') }}">
                        <span class="site-menu-title">Yearly</span>
                    </a>
                </li>

                <li class="site-menu-item {{ Request::is('admin/monthly') ? 'active' : '' }}">
                    <a class="animsition-link" href="{{ route('monthly.index') }}">
                        <span class="site-menu-title">Monthly</span>
                    </a>
                </li>

                <li class="site-menu-item {{ Request::is('admin/daily') ? 'active' : '' }}">
                    <a class="animsition-link" href="{{ route('daily.index') }}">
                        <span class="site-menu-title">Daily</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="site-menu-item has-sub {{ Request::is('admin/inbound/yearly-inbound', 'admin/inbound/monthly-inbound', 'admin/inbound/daily-inbound') ? 'active' : '' }}">
            <a href="javascript:void(0)">
                <i class="site-menu-icon md-view-compact" aria-hidden="true"></i>
                <span class="site-menu-title">Inbound</span>
                <span class="site-menu-arrow"></span>
            </a>
            <ul class="site-menu-sub">
                <li class="site-menu-item {{ Request::is('admin/inbound/daily-inbound') ? 'active' : '' }}">
                    <a class="animsition-link" href="{{ route('daily-inbound.index') }}">
                        <span class="site-menu-title">Daily</span>
                    </a>
                </li>

                <li class="site-menu-item {{ Request::is('admin/inbound/monthly-inbound') ? 'active' : '' }}">
                    <a class="animsition-link" href="{{ route('monthly-inbound.index') }}">
                        <span class="site-menu-title">Monthly</span>
                    </a>
                </li>

                <li class="site-menu-item {{ Request::is('admin/inbound/yearly-inbound') ? 'active' : '' }}">
                    <a class="animsition-link" href="{{ route('yearly-inbound.index') }}">
                        <span class="site-menu-title">Yearly</span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>

<div class="site-gridmenu">
    <div>
        <div>
            <ul>
                <li>
                    <a href="apps/mailbox/mailbox.html">
                        <i class="icon md-email"></i>
                        <span>Mailbox</span>
                    </a>
                </li>
                <li>
                    <a href="apps/calendar/calendar.html">
                        <i class="icon md-calendar"></i>
                        <span>Calendar</span>
                    </a>
                </li>
                <li>
                    <a href="apps/contacts/contacts.html">
                        <i class="icon md-account"></i>
                        <span>Contacts</span>
                    </a>
                </li>
                <li>
                    <a href="apps/media/overview.html">
                        <i class="icon md-videocam"></i>
                        <span>Media</span>
                    </a>
                </li>
                <li>
                    <a href="apps/documents/categories.html">
                        <i class="icon md-receipt"></i>
                        <span>Documents</span>
                    </a>
                </li>
                <li>
                    <a href="apps/projects/projects.html">
                        <i class="icon md-image"></i>
                        <span>Project</span>
                    </a>
                </li>
                <li>
                    <a href="apps/forum/forum.html">
                        <i class="icon md-comments"></i>
                        <span>Forum</span>
                    </a>
                </li>
                <li>
                    <a href="index.html">
                        <i class="icon md-view-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>